testing coloring without tput

diff --git a/libexec/bats-format-simple b/libexec/bats-format-simple
--- a/libexec/bats-format-simple
+++ b/libexec/bats-format-simple
@@ -28,15 +28,15 @@ finish_suite() {
 
 trap finish_suite EXIT
 
-reset=$(tput sgr0)
-green=$(tput setaf 2)
-red=$(tput setaf 1)
-yellow=$(tput setaf 3)
-cyan=$(tput setaf 6)
+#reset=$(tput sgr0)
+reset="\e[0m"
+green="\e[32m"
+red="\e[31m"
+cyan="\e[36m"
 
-tests_skipped=0
-tests_failed=0
-tests_passed=0
+skipped=0
+failed=0
+passed=0
 
 while IFS= read -r line; do
   a=($line)
@@ -46,15 +46,15 @@ while IFS= read -r line; do
   "ok "* )
     if [ "${a[2]} ${a[3]} " == "# skip " ]; then
       echo -e "  ${cyan}- skipped: ${a[@]:4}${reset}"
-      let tests_skipped+=1
+      let skipped+=1
     else
       echo -e "  ${green}✓ ${a[@]:2}${reset}"
-      let tests_passed+=1
+      let passed+=1
     fi
     ;;
   "not ok "* )
     echo -e "  ${red}✗ ${a[@]:3}${reset}"
-    let tests_failed+=1
+    let failed+=1
     ;;
   "# "* )
     echo -e "     ${red}${a[@]:1}${reset}"
@@ -63,7 +63,7 @@ while IFS= read -r line; do
 done
 
 echo
-echo "$(( ${tests_failed} + ${tests_passed} +  ${tests_skipped} )) tests, ${tests_failed} failure, ${tests_skipped} skipped"
+echo "$(( ${failed} + ${passed} +  ${skipped} )) tests, ${failed} failure, ${skipped} skipped"
 
-[ "${tests_failed}" == "0" ] && exit 0 || exit 1
+[ "${failed}" == "0" ] && exit 0 || exit 1
 
